# Generated by Django 5.0.5 on 2024-10-14 16:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('costs', '0002_task_priority_task_progress'),
    ]

    operations = [
        migrations.AddField(
            model_name='cost',
            name='category',
            field=models.CharField(choices=[('food', 'Jedzenie'), ('utilities', 'Rachunki'), ('entertainment', 'Rozrywka'), ('transportation', 'Transport'), ('transportation', 'Zdrowie'), ('transportation', 'Transport'), ('other', 'Inne')], default='other', max_length=15),
        ),
    ]
