# Generated by Django 5.0.5 on 2024-11-02 18:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('costs', '0005_alter_cost_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cost',
            name='category',
            field=models.CharField(choices=[('jedzenie', 'Jedzenie'), ('rachunki', 'Rachunki'), ('rozrywka', 'Rozrywka'), ('transport', 'Transport'), ('zdrowie', 'Zdrowie'), ('inne', 'Inne')], default='inne', max_length=15),
        ),
    ]
